// Code generated by protoc-gen-zig
///! package files
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const File = struct {
    name: ManagedString = .Empty,
    len: i32 = 0,

    pub const _desc_table = .{
        .name = fd(1, .String),
        .len = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
